//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesteBem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int ID { get; set; }
        public string ClienteID { get; set; }
        public int ProdutoID { get; set; }
        public int Quantidade { get; set; }
        public Nullable<System.DateTime> DataCompra { get; set; }
        public bool NoCart { get; set; }
        public string Tamanho { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
