//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesteBem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedores
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> TipoID { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> PaisID { get; set; }
        public Nullable<int> MoradaID { get; set; }
    
        public virtual FornProduto FornProduto { get; set; }
        public virtual Morada Morada { get; set; }
        public virtual Paises Paises { get; set; }
    }
}
