//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesteBem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Carrinho = new HashSet<Carrinho>();
        }
    
        public int ID { get; set; }
        public int TipoID { get; set; }
        public string Nome { get; set; }
        public Nullable<double> Preco { get; set; }
        public string Descricao { get; set; }
        public string Image { get; set; }
        public Nullable<int> TipoRID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Tipo_Produto Tipo_Produto { get; set; }
        public virtual TipoRoupa TipoRoupa { get; set; }
    }
}
